name: CI

on: [push, pull_request]

jobs:
  linux:
    name: "Ubuntu Latest (GNU 9.3.0)"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -p125463"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 125463
          MYSQL_DATABASE: casbin
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h "127.0.0.1" -uroot -p125463 --silent; do
            echo 'Waiting for MySQL...'
            sleep 1
          done

      - name: Configuring CMake files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=ON

      - name: Building library
        run: |
          cd build
          cmake --build . --config Release --target all -j 10 --

      - name: Tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: 125463
          MYSQL_DATABASE: casbin
        run: |
          cd build
          ctest -j10 -C Release -T test --output-on-failure

      - name: Cleanup
        run: |
          rm -r build

  windows:
    name: "Windows Latest (MSVC 19.29)"
    runs-on: windows-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Configuring CMake files
        id: building-files
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Building library
        id: building-lib
        run: |
          cd build
          cmake --build . --config Debug --target casbin sqlpp11::sqlpp11 sqlpp11::mysql nlohmann_json::nlohmann_json GTest::gtest_main GTest::gtest 11sql_test -j 10 --

      - name: Running Tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: 125463
          MYSQL_DATABASE: casbin
        run: |
          cd build
          ctest -j10 -C Release -T test --output-on-failure

  macos:
    name: "macOS Latest (AppleClang 12.0)"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          brew install mysql
          brew install mysql-connector-c
          export MYSQL_ROOT_DIR=$(brew --prefix mysql)
          export MYSQL_INCLUDE_DIR=$MYSQL_ROOT_DIR/include
          export MYSQL_LIB_DIR=$MYSQL_ROOT_DIR/lib

      - name: Configuring CMake files
        env:
          MYSQL_INCLUDE_DIR: ${{ env.MYSQL_INCLUDE_DIR }}
          MYSQL_LIBRARY: ${{ env.MYSQL_LIB_DIR }}/libmysqlclient.dylib
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/local -DMYSQL_INCLUDE_DIR=${MYSQL_INCLUDE_DIR} -DMYSQL_LIBRARY=${MYSQL_LIBRARY} -DENABLE_TESTING=ON

      - name: Building library
        run: |
          cd build
          cmake --build . --config Debug --target all install -j 10 --

      - name: Tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: 125463
          MYSQL_DATABASE: casbin
        run: |
          cd build  
          ctest -j10 -C Release -T test --output-on-failure

      - name: Cleanup
        run: |
          rm -r build
